swagger: '2.0'
info:
  description: API Creacion de usuarios
  version: '1.0'
  title: API Creacion de usuarios
  termsOfService: http://test.com/terms
  contact:
    name: Juan Mercado
    url: https://test.com
    email: apis@test.com
  license:
    name: LICENSE
    url: LICENSE URL
host: localhost:8080
basePath: /
tags:
  - name: health-check-controller
    description: Health Check Controller
  - name: user-controller
    description: User Controller
paths:
  /health:
    get:
      tags:
        - health-check-controller
      summary: healthCheck
      operationId: healthCheckUsingGET
      produces:
        - '*/*'
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /user/:
    post:
      tags:
        - user-controller
      summary: create
      operationId: createUsingPOST
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: user
          description: user
          required: true
          schema:
            $ref: '#/definitions/UserModel'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/InfoResponse'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
    put:
      tags:
        - user-controller
      summary: update
      operationId: updateUsingPUT
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: user
          description: user
          required: true
          schema:
            $ref: '#/definitions/UserModel'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/InfoResponse'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /user/getAll:
    get:
      tags:
        - user-controller
      summary: getAll
      operationId: getAllUsingGET
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/UserModel'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /user/{uuid}:
    get:
      tags:
        - user-controller
      summary: getById
      operationId: getByIdUsingGET
      produces:
        - application/json
      parameters:
        - name: uuid
          in: path
          description: uuid
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/UserModel'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
    delete:
      tags:
        - user-controller
      summary: delete
      operationId: deleteUsingDELETE
      produces:
        - '*/*'
      parameters:
        - name: uuid
          in: path
          description: uuid
          required: true
          type: string
      responses:
        '200':
          description: OK
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      deprecated: false
definitions:
  InfoResponse:
    type: object
    properties:
      active:
        type: boolean
      created:
        type: string
      id:
        type: string
      lastLogin:
        type: string
      modified:
        type: string
      token:
        type: string
    title: InfoResponse
  PhoneModel:
    type: object
    properties:
      cityCode:
        type: string
      countryCode:
        type: string
      number:
        type: string
    title: PhoneModel
  UserModel:
    type: object
    properties:
      active:
        type: boolean
      email:
        type: string
      name:
        type: string
      password:
        type: string
      phones:
        type: array
        items:
          $ref: '#/definitions/PhoneModel'
      uuid:
        type: string
    title: UserModel
